##################################################################################################
# Catalog service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: catalogs
  labels:
    app: catalogs
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: catalogs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogs-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogs
        version: v1
    spec:
      containers:
      - name: catalogs
        image: shopping-cart/catalogs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
##################################################################################################
# Security service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: security
  labels:
    app: security
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: security
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: security-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: security
        version: v1
    spec:
      containers:
      - name: security
        image: shopping-cart/security:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
##################################################################################################
# Email service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  ports:
  - name: smtp
    port: 25
    targetPort: 1025
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: email-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: email-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
        version: v1
    spec:
      containers:
      - name: email-service
        image: djfarrelly/maildev:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 25
          protocol: TCP
        - containerPort: 80
          protocol: TCP
---
##################################################################################################
# Ambassador service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: catalogs_mapping
      prefix: /c/
      service: catalogs:80
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: security_mapping
      prefix: /id/
      service: security:80
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: email_mapping
      prefix: /e/
      service: email-service:80
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
---