##################################################################################################
# Catalog service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: catalogs
  labels:
    app: catalogs
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: catalogs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogs-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogs
        version: v1
    spec:
      containers:
      - name: catalogs
        image: shopping-cart/catalogs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
##################################################################################################
# Email service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  ports:
  - name: smtp
    port: 25
    targetPort: smtp
  - name: http
    port: 80
  selector:
    app: email-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: email-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
        version: v1
    spec:
      containers:
      - name: email-service
        image: djfarrelly/maildev:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 25
        - containerPort: 80
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: email-service
          servicePort: 80
      - path: /api.*
        backend:
          serviceName: catalogs
          servicePort: 80
---